# Generated by Django 3.1.6 on 2021-04-22 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GFL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_admin', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, default='2021-04-25', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, default='2021-04-14'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GFL.admin_class'),
        ),
    ]
